name: url_navigator
description: A flutter navigate framework based on flutter navigator 2.0, which use simple url(in both full-path and relative-path way) to navigate, providing a better performance on browser for your app.
version: 0.0.4
homepage: https://github.com/jkouubb/url_navigator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
